[workspace]
authors = ["Tuatini Godard <email@tuatini.me>"]
channels = ["conda-forge"]
name = "gym"
platforms = ["linux-64"]
version = "0.1.0"

[system-requirements]
cuda = "12.4"

[dependencies]
python = "3.13.*"
pytorch = "*"
matplotlib = ">=3.10.1,<4"
opencv = ">=4.11.0,<5"
imageio = ">=2.37.0,<3"
tqdm = ">=4.67.1,<5"
imageio-ffmpeg = ">=0.6.0,<0.7"

[pypi-dependencies]
pillow = "*"
gymnasium = { version = "*", extras = ["box2d"] }
ale-py = "*"
