[workspace]
authors = ["Tuatini Godard <email@tuatini.me>"]
channels = ["conda-forge"]
name = "unit1"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[system-requirements]
cuda = "12.4"

[dependencies]
python = ">=3.11.0"
jupyterlab = "*"
pytorch = "*"
numpy = "*"
ipywidgets = "*"
tqdm = ">=4.67.1,<5"
moviepy = ">=1.0.3,<2"
pygame = "*"
huggingface_hub = "*"
pyyaml = "*"
imageio = "*"
imageio-ffmpeg = "*"
pyglet = ">=2.1.5,<3"
opencv = ">=4.11.0,<5"
pyopengl = ">=3.1.9,<4"
ffmpeg = ">=7.1.1,<8"
xvfbwrapper = ">=0.2.10,<0.3"
optuna = ">=4.3.0,<5"

[pypi-dependencies]
gymnasium = { version = "*"}
pyvirtualdisplay = ">=3.0, <4"
panda-gym = ">=3.0.7, <4"
huggingface-sb3 = ">=3.0, <4"
stable-baselines3 = { version = "*", extras = ["extra"] }
