[workspace]
authors = ["Tuatini Godard <email@tuatini.me>"]
channels = ["conda-forge"]
name = "unit1"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[system-requirements]
cuda = "12.1"

[dependencies]
python = "3.12.*"
pytorch = "*"
numpy = "*"
tqdm = "*"
pygame = "*"
pyyaml = "*"
imageio = "*"
imageio-ffmpeg = "*"
pyglet = ">=2.1.5,<3"
opencv = ">=4.11.0,<5"
tyro = ">=0.9.20,<0.10"
tensorboard = ">=2.19.0,<3"
#pyglet = "1.5.*"

[pypi-dependencies]
gymnasium = { version = "*", extras = ["all", "atari"] }
pyvirtualdisplay = ">=3.0, <4"
rl-zoo3 = { git = "https://github.com/DLR-RM/rl-baselines3-zoo" }
ale-py = ">=0.11.0, <0.12"
