[workspace]
authors = ["Tuatini Godard <email@tuatini.me>"]
channels = ["conda-forge"]
name = "unit1"
platforms = ["linux-64"]
version = "0.1.0"

[system-requirements]
cuda = "12.1"

[dependencies]
python = "==3.10.12"
jupyterlab="*"
ujson="*"
#pytorch = "*"
#pyvirtualdisplay = ">=3.0,<4"
#ipywidgets = "*"
#moviepy = ">=1.0.3,<2"

[pypi-dependencies]
mlagents_envs = { git = "https://github.com/Unity-Technologies/ml-agents.git", branch = "release_22", subdirectory = "ml-agents-envs" }
mlagents = { git = "https://github.com/Unity-Technologies/ml-agents.git", branch = "release_22", subdirectory = "ml-agents" }
swig = "*"
stable-baselines3 = "==2.0.0"
gymnasium = { version = "*", extras = ["box2d"] }
huggingface-sb3 = ">=3.0, <4"
shimmy = ">=1.3.0, <2"
