[workspace]
authors = ["Tuatini Godard <email@tuatini.me>"]
channels = ["conda-forge"]
name = "unit1"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[system-requirements]
cuda = "12.4"

[dependencies]
python = ">=3.10.1,<=3.10.12"
jupyterlab = "*"
#pytorch = ">=2.1.1"
numpy = ">=1.13.3,<2.0"
ipywidgets = "*"
tqdm = "*"
huggingface_hub = "*"
pyyaml = ">=3.1.0"
ujson = ">=5.10.0"
grpcio = ">=1.11.0"
cloudpickle = ">=3.1.1,<4"
pillow = ">=4.2.1"
protobuf = ">=3.6"
gym = ">=0.21.0"
filelock = ">=3.4.0"
tensorflow = ">=2.10.0"


[pypi-dependencies]
pettingzoo = "==1.15.0"
mlagents = "*"
