[workspace]
authors = ["Tuatini Godard <email@tuatini.me>"]
channels = ["conda-forge"]
name = "unit1"
platforms = ["linux-64"]
version = "0.1.0"

[system-requirements]
cuda = "12.1"

[dependencies]
python="3.11.*"
jupyterlab="*"
pytorch = "*"
pyvirtualdisplay = ">=3.0,<4"
ipywidgets = "*"
moviepy = ">=1.0.3,<2"

[pypi-dependencies]
swig = "*"
stable-baselines3 = "==2.0.0"
gymnasium = { version = "*", extras = ["box2d"] }
huggingface-sb3 = ">=3.0, <4"
shimmy = ">=1.3.0, <2"
